pipeline:
  identifier: Build_shiftleft_js_demo_1695748538967
  name: Build qwiet-js-demo
  orgIdentifier: default
  projectIdentifier: HARQwietjs
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1695748478670
        repoName: JoeFerrin/shiftleft-js-demo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: node
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    shell: Sh
                    command: |
                      npm install
                      rm -rf node_modules
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: apt update
                  identifier: apt_update
                  spec:
                    shell: Sh
                    command: apt update && apt install -y curl jq
              - step:
                  type: Run
                  name: curl sl
                  identifier: curl_sl
                  spec:
                    shell: Sh
                    command: curl https://cdn.shiftleft.io/download/sl >/usr/local/bin/sl && chmod a+rx /usr/local/bin/sl
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
    - stage:
        name: PreZero Scan
        identifier: PreZero_Scan
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: SL Analyze
                  identifier: SL_Analyze
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          #!/bin/bash
                          sl analyze --app HAR-Qwiet-js --container 18fgsa/s3-resource --js .
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10s
        tags: {}
