pipeline:
  identifier: Build_shiftleft_js_demo_1695829398465
  name: Build shiftleft-js-demo
  orgIdentifier: default
  projectIdentifier: HARQwietjsdemo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1695829315182
        repoName: JoeFerrin/shiftleft-js-demo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build-NODE
                  spec:
                    connectorRef: DockerNode
                    image: plugins/docker
                    settings:
                      tags: latest
                  timeout: ""
                  type: Plugin
                  description: Node.js Docker build
                  when:
                    stageStatus: Success
              - step:
                  type: Run
                  name: CURL sl
                  identifier: CURL_sl
                  spec:
                    shell: Sh
                    command: curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
              - step:
                  type: Run
                  name: RUN sl analyze
                  identifier: RUN_sl_analyze
                  spec:
                    shell: Sh
                    command: sl analyze --app HAR-Qwiet-js-demo
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
